thing=["mozzarella", "cinderella ", "salmonella"]
print("Initial list of things")
print(thing)
thing[1]=thing[1].capitalize()
print("List with person being capitalized")
print(thing)
thing[0]=thing[0].upper()
print("List with cheesy thing converted to upper")
print(thing)
print("List with disease removed ")
thing.remove(thing[2])
print(thing)
#add this if that is what is mend
print("List with new element")
thing.append("Noble Prize")
print(thing)